set termguicolors
set background=dark

" --------- System Config -----------------------------------------------------
set title " Allow VIM to retitle the terminal
set history=100 " Allow a lot more history
set nocompatible " Disable old-time Vim compat
let mapleader = "\<Space>"
let g:mapleader = "\<Space>"
set t_ti= t_te= " prevent Vim from clearing screen when exiting

" --------- Environment
set directory=$XDG_CACHE_HOME/vim/swap//,~//,/tmp//
set backupdir=$XDG_CACHE_HOME/vim/backup//,~//,/tmp//
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set undodir=$XDG_CACHE_HOME/vim/undo//,~//,/tmp//
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
set packpath+=$XDG_CONFIG_HOME/vim
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

syntax on
filetype plugin indent on

colorscheme nord
let base16colorspace=256  " Access colors present in 256 colorspace

" --------- Searching
set incsearch " Search as we type
set hlsearch " highlight all matches
set ignorecase
set smartcase
set magic " Regexp magic

" --------- Errors
set noerrorbells
set visualbell t_vb=[?5h$<100/>[?5l

" --------- Matching enclosures
set showmatch " Highlight matching parens
set mat=2 " Blink matching parents

" --------- Line numbers
set number " Show line numbers
set relativenumber " Relative numbers for all but the current line
set cursorline " Add an indicator for the current line
set colorcolumn=90 " Guard at line 90, yellow light
highlight ColorColumn ctermbg=3*

" ---------- Completion (using mucomplete)
set completeopt+=menuone,longest,noselect,noinsert
let g:peekaboo_ins_prefix = '<c-x>' " c-r incompatible with mucomplete

" --------- Files
" Read ffiles when changed from the outside
set autoread
" Fast saving and sudo saving
nmap <leader>w :w!<cr>
command W w !sudo tee % > /dev/null
" Unix as standard
set ffs=unix,dos,mac

" Protect changes between writes. Default values of
" updatecount (200 keystrokes) and updatetime
" (4 seconds) are fine
set swapfile
" protect against crash-during-write
set writebackup
" but do not persist backup after successful write
set nobackup
" use rename-and-write-new method whenever safe
set backupcopy=auto
" persist the undo tree for each file
set undofile

" --------- Statusbar (using Lightline)
set laststatus=2 " Allow a status bar
let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }
set noshowmode " Dont't show mode as we use lightline plugin

" --------- EasyMotion bindings
"let g:EasyMotion_do_mapping = 0 " Disable default mappings
" Turn on case insensitive feature
let g:EasyMotion_smartcase = 1
" Only use these keys for jump highlights as some of the default keys are
" difficult to read or to reach
let g:EasyMotion_keys='qwertzuiopasdlkjf'
" s{char}{label} for basic jumping
nmap s <Plug>(easymotion-overwin-f2)
" Line movement
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader><down> <Plug>(easymotion-j)
map <Leader><up> <Plug>(easymotion-k)

" --------- GitGutter Plugin
let g:gitgutter_override_sign_column_highlight = 0 " let NeoSolarized override colors
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '>'
let g:gitgutter_sign_removed = 'x'
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = 'w'

" --------- vim wiki
let g:wiki_root = getenv("BOOKMARKS_DIR") . "/notes"

" --------- fzf Plugin
source /usr/share/doc/fzf/examples/fzf.vim

nnoremap <C-f> :Files<CR>
nnoremap <C-b> :Buffers<CR>

" --------- Move Lines
nnoremap <C-Down> :m .+1<CR>==
nnoremap <C-Up> :m .-2<CR>==
inoremap <C-Down> <Esc>:m .+1<CR>==gi
inoremap <C-Up> <Esc>:m .-2<CR>==gi
vnoremap <C-Down> :m '>+1<CR>gv=gv
vnoremap <C-Up> :m '<-2<CR>gv=gv

" run macro in register q by hitting <space> in normal mode
nnoremap <Space> @q

" disable search highlights until next search
nnoremap <C-x> :nohlsearch<CR>

" copy and paste from system clipboard
:inoremap <C-v> <ESC>"+pa
:vnoremap <C-c> "+y
:vnoremap <C-d> "+d

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file)
imap <c-x><c-l> <plug>(fzf-complete-line)

" netrw config
let g:netrw_banner = 0
let g:netrw_liststyle = 3

:nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
runtime ftplugin/man.vim

" Open diffs in vertical splits
" Use 'xdiff' library options: patience algorithm with indent-heuristics (same to Git options)
" NOTE: vim uses the external diff utility which doesn't do word diffs nor can it find moved-and-modified lines.
" NOTE: still this algorithm is worse than "delta" or "DiffMerge"
" See: https://stackoverflow.com/questions/36519864/the-way-to-improve-vimdiff-similarity-searching-mechanism
" See: https://vimways.org/2018/the-power-of-diff/
set diffopt=internal,filler,vertical,context:5,foldcolumn:1,indent-heuristic,algorithm:patience

command! FormatXML :%!python3 -c "import xml.dom.minidom, sys; print(xml.dom.minidom.parse(sys.stdin).toprettyxml())"
command! FormatJSON :%!python3 -m json.tool

function! FzfSpellSink(word)
  exe 'normal! "_ciw'.a:word
endfunction

function! FzfSpell()
  let suggestions = spellsuggest(expand("<cword>"))
  return fzf#run({'source': suggestions, 'sink': function("FzfSpellSink"), 'down': 10 })
endfunction

nnoremap z= :call FzfSpell()<CR>
inoremap <C-s> <c-g>u<Esc>[s1z=`]a<c-g>u
